-- The D1 schema for rustdesk-selfhost-api.
--
-- GENERATED BY HAND — keep in sync with `src/schema.ts`, which is the source of
-- truth and is what the Worker applies lazily. `run-contract-test.sh` compares
-- the two table sets on every run, so drift fails the suite rather than
-- surfacing later as "no such table" on a fresh database.
--
-- Apply with:
--   npx wrangler d1 execute rustdesk-selfhost-api --remote --file=./schema.sql
--
-- This is optional: the Worker bootstraps and migrates its own tables on first
-- use. Applying it up front just makes the first request quiet.
--
-- The trailing `_meta` upsert records the revision, so a database created from
-- this file is immediately at the current schema revision and the Worker skips
-- the migration path entirely.

CREATE TABLE IF NOT EXISTS _meta (
  key TEXT PRIMARY KEY, value TEXT NOT NULL DEFAULT '');

-- -- accounts ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
  name          TEXT PRIMARY KEY,
  display_name  TEXT NOT NULL DEFAULT '',
  avatar        TEXT NOT NULL DEFAULT '',
  email         TEXT NOT NULL DEFAULT '',
  note          TEXT NOT NULL DEFAULT '',
  is_admin      INTEGER NOT NULL DEFAULT 0,
  status        INTEGER NOT NULL DEFAULT 1,
  password_hash TEXT NOT NULL DEFAULT '',
  tfa_secret    TEXT NOT NULL DEFAULT '',
  tfa_type      TEXT NOT NULL DEFAULT '',
  strategy_name TEXT NOT NULL DEFAULT '',
  verifier      TEXT NOT NULL DEFAULT '',
  created_at    REAL NOT NULL);

CREATE TABLE IF NOT EXISTS tokens (
  token      TEXT PRIMARY KEY,
  user_name  TEXT NOT NULL,
  created_at REAL NOT NULL,
  expires_at REAL NOT NULL DEFAULT 0);

-- -- address books -----------------------------------------------------------
CREATE TABLE IF NOT EXISTS address_books (
  guid       TEXT PRIMARY KEY,
  user_name  TEXT NOT NULL,
  name       TEXT NOT NULL,
  kind       TEXT NOT NULL,
  owner      TEXT NOT NULL DEFAULT '',
  rule       INTEGER NOT NULL DEFAULT 3,
  note       TEXT NOT NULL DEFAULT '',
  info       TEXT NOT NULL DEFAULT '{}',
  created_at REAL NOT NULL);

CREATE TABLE IF NOT EXISTS ab_peers (
  guid       TEXT NOT NULL,
  id         TEXT NOT NULL,
  payload    TEXT NOT NULL,
  tags       TEXT NOT NULL DEFAULT '[]',
  updated_at REAL NOT NULL,
  PRIMARY KEY (guid, id));

CREATE TABLE IF NOT EXISTS ab_tags (
  guid  TEXT NOT NULL,
  name  TEXT NOT NULL,
  color INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (guid, name));

-- Who an address book is shared with. `target_kind` is user | group | everyone.
CREATE TABLE IF NOT EXISTS ab_rules (
  guid        TEXT PRIMARY KEY,
  ab_guid     TEXT NOT NULL,
  target_kind TEXT NOT NULL,
  target      TEXT NOT NULL DEFAULT '',
  rule        INTEGER NOT NULL DEFAULT 1,
  created_at  REAL NOT NULL);

-- -- devices -----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS devices (
  id                TEXT PRIMARY KEY,
  user_name         TEXT NOT NULL DEFAULT '',
  device_group_name TEXT NOT NULL DEFAULT '',
  strategy_name     TEXT NOT NULL DEFAULT '',
  note              TEXT NOT NULL DEFAULT '',
  status            INTEGER NOT NULL DEFAULT 1,
  info              TEXT NOT NULL DEFAULT '{}',
  payload           TEXT NOT NULL DEFAULT '{}',
  pk                TEXT NOT NULL DEFAULT '',
  uuid              TEXT NOT NULL DEFAULT '',
  ver               TEXT NOT NULL DEFAULT '',
  ip                TEXT NOT NULL DEFAULT '',
  conns             TEXT NOT NULL DEFAULT '[]',
  last_online       REAL NOT NULL DEFAULT 0,
  created_at        REAL NOT NULL,
  updated_at        REAL NOT NULL);

CREATE TABLE IF NOT EXISTS device_groups (
  guid       TEXT NOT NULL DEFAULT '',
  user_name  TEXT NOT NULL,
  name       TEXT NOT NULL,
  created_at REAL NOT NULL,
  PRIMARY KEY (user_name, name));

-- Connection ids the operator asked to drop; drained by /api/heartbeat.
CREATE TABLE IF NOT EXISTS device_commands (
  device_id  TEXT NOT NULL,
  kind       TEXT NOT NULL,
  payload    TEXT NOT NULL DEFAULT '{}',
  created_at REAL NOT NULL);

-- -- strategy / policy -------------------------------------------------------
CREATE TABLE IF NOT EXISTS strategies (
  name        TEXT PRIMARY KEY,
  payload     TEXT NOT NULL DEFAULT '{}',
  modified_at REAL NOT NULL,
  created_at  REAL NOT NULL);

-- -- audit -------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS audit_conn (
  guid           TEXT PRIMARY KEY,
  nonce          TEXT NOT NULL DEFAULT '',
  id             TEXT NOT NULL DEFAULT '',
  uuid           TEXT NOT NULL DEFAULT '',
  conn_id        INTEGER NOT NULL DEFAULT 0,
  session_id     INTEGER NOT NULL DEFAULT 0,
  peer_id        TEXT NOT NULL DEFAULT '',
  ip             TEXT NOT NULL DEFAULT '',
  action         TEXT NOT NULL DEFAULT '',
  conn_type      INTEGER NOT NULL DEFAULT 0,
  conn_audit_ref TEXT NOT NULL DEFAULT '',
  note           TEXT NOT NULL DEFAULT '',
  created_at     REAL NOT NULL);

CREATE TABLE IF NOT EXISTS audit_file (
  guid       TEXT PRIMARY KEY,
  nonce      TEXT NOT NULL DEFAULT '',
  id         TEXT NOT NULL DEFAULT '',
  uuid       TEXT NOT NULL DEFAULT '',
  peer_id    TEXT NOT NULL DEFAULT '',
  conn_id    INTEGER NOT NULL DEFAULT 0,
  type       INTEGER NOT NULL DEFAULT 0,
  path       TEXT NOT NULL DEFAULT '',
  is_file    INTEGER NOT NULL DEFAULT 0,
  info       TEXT NOT NULL DEFAULT '{}',
  created_at REAL NOT NULL);

CREATE TABLE IF NOT EXISTS audit_alarm (
  guid       TEXT PRIMARY KEY,
  nonce      TEXT NOT NULL DEFAULT '',
  id         TEXT NOT NULL DEFAULT '',
  uuid       TEXT NOT NULL DEFAULT '',
  typ        INTEGER NOT NULL DEFAULT 0,
  info       TEXT NOT NULL DEFAULT '{}',
  conn_id    INTEGER NOT NULL DEFAULT 0,
  created_at REAL NOT NULL);

CREATE TABLE IF NOT EXISTS audit_notes (
  guid       TEXT PRIMARY KEY,
  note       TEXT NOT NULL DEFAULT '',
  updated_at REAL NOT NULL);

-- -- recordings --------------------------------------------------------------
CREATE TABLE IF NOT EXISTS records (
  file       TEXT PRIMARY KEY,
  size       INTEGER NOT NULL DEFAULT 0,
  chunks     INTEGER NOT NULL DEFAULT 0,
  state      TEXT NOT NULL DEFAULT 'open',
  created_at REAL NOT NULL,
  updated_at REAL NOT NULL);

-- -- misc --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS oidc_sessions (
  code       TEXT PRIMARY KEY,
  user_name  TEXT NOT NULL DEFAULT '',
  authed     INTEGER NOT NULL DEFAULT 0,
  created_at REAL NOT NULL);

CREATE TABLE IF NOT EXISTS switch_grants (
  id         TEXT PRIMARY KEY,
  verifier   TEXT NOT NULL DEFAULT '',
  signature  TEXT NOT NULL DEFAULT '',
  verified   INTEGER NOT NULL DEFAULT 0,
  created_at REAL NOT NULL);

-- -- indexes -----------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_ab_peers_guid ON ab_peers (guid, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_ab_rules_ab ON ab_rules (ab_guid);
CREATE INDEX IF NOT EXISTS idx_address_books_user ON address_books (user_name, kind);
CREATE INDEX IF NOT EXISTS idx_devices_user ON devices (user_name, last_online DESC);
CREATE INDEX IF NOT EXISTS idx_audit_conn_created ON audit_conn (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_file_created ON audit_file (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_alarm_created ON audit_alarm (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_records_updated ON records (updated_at DESC);

-- -- schema revision ---------------------------------------------------------
-- Must match SCHEMA_VERSION in src/env.ts.
INSERT INTO _meta (key, value) VALUES ('schema_version', '2')
  ON CONFLICT(key) DO UPDATE SET value = excluded.value;
